language: node_js
node_js:
- '6'
deploy:
  provider: heroku
  api_key:
    secure: 0ffFLyootpVyoiIJdMqoVePeAO0YJCRjmVkscGmv9Ifs9h5/U5SkLDSBmAhJfJXwOlIGPTdaRavdldraTOb7V2+OdpqdoFw50AssqjeNuO55g5d9a9YM+ky2x1M7KA2A1zBvrqL6caLcNzZKyXAPYPOPo0D6/t6Lfu70t+izNNoF2DkrI0CbxWH3CSDRaPLnaptgPpoztiMBi/OrN8b0ksYgRCI2ffyTRwV6PGjiBqlYZ/b+RwaFI5TrFkSAWS53ksPrZtvyVjD10XXit/+/ObxAc1f2GOUZi8HSxWzv7qj2LPCONrsBupVjGYwxwYth2lKhZ5gtxEz1BmVJIDEzrvxz7nNn3d2vujlsvg/c4CKLjQqxK41Y0l1ZlzIEDvaBgle2deGCto1cxy4xrlGhboE5776EOGdFyj3Sxnn0K6drcnjTXyQBVKvrDO6wVsoXwr4qS18ZZBJFDjNVfySY9LeszxgM5rLS/FBX+Co4yVscrrmJ//CcTdLJNeygOeKZHBI3SwPpuF1S/ZCgNLbvkFpROtpD1XCBBIKL1mH1A2kcmY1sFYc8Fs29D7uH1bp8P4HHVdF/qJ6K88Z3N+u4GDgMjqNfQ0lPbI42RQ6zxtt1iZ2pt/CrsLXh35MqtN4RTsqxGOxQQMgXqhuqsIBryjlELsTJS7IX6lTIRhiVxS0=
